export const actionsWquestions = [
	{
		type: 'Wo',
		aux: 'hat',
		participle: 'beworben',
		reflexive: 'sich',
		object: '',
		place: 'bei Siemens',
		time: 'letzte Woche',
	},
	{
		type: 'Wann',
		aux: 'hat',
		participle: 'abgeschlossen',
		reflexive: '',
		object: 'ihr Studium',
		place: 'an der Uni',
		time: '',
	},
	{
		type: 'An welchem Kurs',
		aux: 'hat',
		participle: 'teilgenommen',
		reflexive: '',
		object: '',
		place: '',
		time: 'vor zwei Monaten',
	},
	{
		type: 'Mit wem',
		aux: 'hat',
		participle: 'besprochen',
		reflexive: '',
		object: 'das Projekt',
		place: 'im Büro',
		time: '',
	},
	{
		type: 'Welches Ziel',
		aux: 'hat',
		participle: 'erreicht',
		reflexive: '',
		object: '',
		place: '',
		time: 'im letzten Semester',
	},
	{
		type: 'Mit wem',
		aux: 'hat',
		participle: 'verhandelt',
		reflexive: '',
		object: '',
		place: '',
		time: 'gestern',
	},
	{
		type: 'Was',
		aux: 'hat',
		participle: 'vorbereitet',
		reflexive: '',
		object: '',
		place: '',
		time: 'am Wochenende',
	},
	{
		type: 'Wen',
		aux: 'hat',
		participle: 'überzeugt',
		reflexive: '',
		object: 'von ihrer Idee',
		place: '',
		time: '',
	},
];

export const actionsYesNoQuestions = [
	{
		aux: 'Hat',
		participle: 'unterschrieben',
		object: 'den Vertrag',
		place: '',
		time: 'schon',
	},
	{
		aux: 'Hat',
		participle: 'vorbereitet',
		object: 'die Präsentation',
		place: 'für das Meeting',
		time: '',
	},
	{
		aux: 'Hat',
		participle: 'teilgenommen',
		object: 'an der Schulung',
		place: '',
		time: '',
	},
	{
		aux: 'Hat',
		participle: 'gemacht',
		object: 'Überstunden',
		place: '',
		time: 'gestern',
	},
	{
		aux: 'Hat',
		participle: 'gelöst',
		object: 'das Problem',
		place: 'mit dem Kunden',
		time: '',
	},
	{
		aux: 'Hat',
		participle: 'beantwortet',
		object: 'die E-Mails',
		place: '',
		time: '',
	},
	{
		aux: 'Hat',
		participle: 'abgeschlossen',
		object: 'das Projekt',
		place: '',
		time: 'erfolgreich',
	},
	{
		aux: 'Hat',
		participle: 'eingereicht',
		object: 'die Unterlagen',
		place: '',
		time: 'rechtzeitig',
	},
	{
		aux: 'Hat',
		participle: 'gefunden',
		object: 'eine neue Stelle',
		place: '',
		time: '',
	},
	{
		aux: 'Hat',
		participle: 'dokumentiert',
		object: 'die Ergebnisse',
		place: '',
		time: '',
	},
];

export const statements = [
	{
		subject: 'Lena',
		aux: 'hat',
		object: 'an einer Schulung',
		place: '',
		time: 'letzte Woche',
		participle: 'teilgenommen',
	},
	{
		subject: 'Markus',
		aux: 'hat',
		object: 'die Unterlagen',
		place: '',
		time: 'rechtzeitig',
		participle: 'eingereicht',
	},
	{
		subject: 'Fatima',
		aux: 'musste',
		object: 'Überstunden',
		place: '',
		time: 'gestern',
		participle: 'machen',
	},
	{
		subject: 'Jonas',
		aux: 'hat',
		object: 'das Projekt',
		place: 'mit seinem Kollegen',
		time: '',
		participle: 'besprochen',
	},
	{
		subject: 'Nora',
		aux: 'hat',
		object: 'ihr Studium',
		place: '',
		time: 'erfolgreich',
		participle: 'abgeschlossen',
	},
	{
		subject: 'Sven',
		aux: 'konnte',
		object: 'das Problem',
		place: '',
		time: 'schnell',
		participle: 'lösen',
	},
	{
		subject: 'Marta',
		aux: 'hat',
		reflexive: 'sich',
		object: 'auf eine neue Stelle',
		place: '',
		time: '',
		participle: 'beworben',
	},
	{
		subject: 'Yusuf',
		aux: 'hat',
		object: 'die Ergebnisse',
		place: '',
		time: '',
		participle: 'dokumentiert',
	},
	{
		subject: 'Die Auszubildenden',
		aux: 'haben',
		object: 'an der Prüfung',
		place: '',
		time: 'heute',
		participle: 'teilgenommen',
	},
	{
		subject: 'Der Mitarbeiter',
		aux: 'hat',
		object: 'die Präsentation',
		place: '',
		time: 'für das Meeting',
		participle: 'vorbereitet',
	},
];
