export const TOP100_UNREGELMÄSSIGE_VERBEN = [
	{
		id: 'backen',
		infinitiv: 'backen',
		translation: 'печь',
		prateritum: ['buk', 'backte'],
		partizip2: 'gebacken',
	},
	{
		id: 'befehlen',
		infinitiv: 'befehlen',
		translation: 'приказывать',
		prateritum: ['befahl'],
		partizip2: 'befohlen',
	},
	{
		id: 'beginnen',
		infinitiv: 'beginnen',
		translation: 'начинать',
		prateritum: ['begann'],
		partizip2: 'begonnen',
	},
	{
		id: 'beißen',
		infinitiv: 'beißen',
		translation: 'кусать',
		prateritum: ['biss'],
		partizip2: 'gebissen',
	},
	{
		id: 'denken',
		infinitiv: 'denken',
		translation: 'думать',
		prateritum: ['dachte'],
		partizip2: 'gedacht',
	},
	{
		id: 'dreschen',
		infinitiv: 'dreschen',
		translation: 'молотить',
		prateritum: ['drosch'],
		partizip2: 'gedroschen',
	},
	{
		id: 'dringen',
		infinitiv: 'dringen',
		translation: 'проникать / настаивать',
		prateritum: ['drang'],
		partizip2: 'gedrungen',
	},
	{
		id: 'dürfen',
		infinitiv: 'dürfen',
		translation: 'мочь (иметь разрешение)',
		prateritum: ['durfte'],
		partizip2: 'gedurft',
	},
	{
		id: 'empfehlen',
		infinitiv: 'empfehlen',
		translation: 'рекомендовать',
		prateritum: ['empfahl'],
		partizip2: 'empfohlen',
	},
	{
		id: 'erklimmen',
		infinitiv: 'erklimmen',
		translation: 'взбираться / карабкаться',
		prateritum: ['erklomm', 'erklimmte'],
		partizip2: ['erklommen'],
	},
	{
		id: 'erlöschen',
		infinitiv: 'erlöschen',
		translation: 'гаснуть / потухать',
		prateritum: ['erlosch'],
		partizip2: 'erloschen',
	},
	{
		id: 'erschrecken',
		infinitiv: 'erschrecken',
		translation: 'пугать / пугаться',
		prateritum: ['erschreckte', 'erschrak'],
		partizip2: ['erschreckt'],
	},
	{
		id: 'essen',
		infinitiv: 'essen',
		translation: 'есть',
		prateritum: ['aß'],
		partizip2: 'gegessen',
	},
	{
		id: 'erwägen',
		infinitiv: 'erwägen',
		translation: 'обдумывать / взвешивать',
		prateritum: ['erwog'],
		partizip2: 'erwogen',
	},
	{
		id: 'fahren',
		infinitiv: 'fahren',
		translation: 'ехать / водить',
		prateritum: ['fuhr'],
		partizip2: 'gefahren',
	},
	{
		id: 'fallen',
		infinitiv: 'fallen',
		translation: 'падать',
		prateritum: ['fiel'],
		partizip2: 'gefallen',
	},
	{
		id: 'fangen',
		infinitiv: 'fangen',
		translation: 'ловить',
		prateritum: ['fing'],
		partizip2: 'gefangen',
	},
	{
		id: 'fechten',
		infinitiv: 'fechten',
		translation: 'фехтовать',
		prateritum: ['focht'],
		partizip2: 'gefochten',
	},
	{
		id: 'finden',
		infinitiv: 'finden',
		translation: 'находить',
		prateritum: ['fand'],
		partizip2: 'gefunden',
	},
	{
		id: 'fliegen',
		infinitiv: 'fliegen',
		translation: 'летать',
		prateritum: ['flog'],
		partizip2: 'geflogen',
	},
	{
		id: 'fliehen',
		infinitiv: 'fliehen',
		translation: 'убегать / спасаться',
		prateritum: ['floh'],
		partizip2: 'geflohen',
	},
	{
		id: 'fließen',
		infinitiv: 'fließen',
		translation: 'течь',
		prateritum: ['floss'],
		partizip2: 'geflossen',
	},
	{
		id: 'fressen',
		infinitiv: 'fressen',
		translation: 'жрать (о животных)',
		prateritum: ['fraß'],
		partizip2: 'gefressen',
	},
	{
		id: 'frieren',
		infinitiv: 'frieren',
		translation: 'мёрзнуть / замерзать',
		prateritum: ['fror'],
		partizip2: 'gefroren',
	},
	{
		id: 'gären',
		infinitiv: 'gären',
		translation: 'бродить',
		prateritum: ['gor'],
		partizip2: 'gegoren',
	},
	{
		id: 'gebären',
		infinitiv: 'gebären',
		translation: 'рождать',
		prateritum: ['gebar', 'gebärte'],
		partizip2: 'geboren',
	},
	{
		id: 'geben',
		infinitiv: 'geben',
		translation: 'давать',
		prateritum: ['gab'],
		partizip2: 'gegeben',
	},
	{
		id: 'gedeihen',
		infinitiv: 'gedeihen',
		translation: 'процветать / преуспевать',
		prateritum: ['gedieh'],
		partizip2: 'gediehen',
	},
	{
		id: 'gehen',
		infinitiv: 'gehen',
		translation: 'идти',
		prateritum: ['ging'],
		partizip2: 'gegangen',
	},
	{
		id: 'gelingen',
		infinitiv: 'gelingen',
		translation: 'удаваться',
		prateritum: ['gelang'],
		partizip2: 'gelungen',
	},
	{
		id: 'gelten',
		infinitiv: 'gelten',
		translation: 'считаться / стоить',
		prateritum: ['galt'],
		partizip2: 'gegolten',
	},
	{
		id: 'genesen',
		infinitiv: 'genesen',
		translation: 'выздоравливать',
		prateritum: ['genas'],
		partizip2: 'genesen',
	},
	{
		id: 'genießen',
		infinitiv: 'genießen',
		translation: 'наслаждаться',
		prateritum: ['genoss'],
		partizip2: 'genossen',
	},
	{
		id: 'geschehen',
		infinitiv: 'geschehen',
		translation: 'происходить',
		prateritum: ['geschah'],
		partizip2: 'geschehen',
	},
	{
		id: 'gewinnen',
		infinitiv: 'gewinnen',
		translation: 'выигрывать',
		prateritum: ['gewann'],
		partizip2: 'gewonnen',
	},
	{
		id: 'gießen',
		infinitiv: 'gießen',
		translation: 'лить / поливать',
		prateritum: ['goss'],
		partizip2: 'gegossen',
	},
	{
		id: 'gleichen',
		infinitiv: 'gleichen',
		translation: 'быть похожим',
		prateritum: ['glich'],
		partizip2: 'geglichen',
	},
	{
		id: 'gleiten',
		infinitiv: 'gleiten',
		translation: 'скользить',
		prateritum: ['glitt'],
		partizip2: 'geglitten',
	},
	{
		id: 'graben',
		infinitiv: 'graben',
		translation: 'копать',
		prateritum: ['grub'],
		partizip2: 'gegraben',
	},
	{
		id: 'greifen',
		infinitiv: 'greifen',
		translation: 'хватать / схватывать',
		prateritum: ['griff'],
		partizip2: 'gegriffen',
	},
	{
		id: 'haben',
		infinitiv: 'haben',
		translation: 'иметь',
		prateritum: ['hatte'],
		partizip2: 'gehabt',
	},
	{
		id: 'halten',
		infinitiv: 'halten',
		translation: 'держать / останавливаться',
		prateritum: ['hielt'],
		partizip2: 'gehalten',
	},
	{
		id: 'hängen',
		infinitiv: 'hängen',
		translation: 'висеть',
		prateritum: ['hing'],
		partizip2: 'gehangen',
	},
	{
		id: 'heben',
		infinitiv: 'heben',
		translation: 'поднимать',
		prateritum: ['hob'],
		partizip2: 'gehoben',
	},
	{
		id: 'heißen',
		infinitiv: 'heißen',
		translation: 'называться',
		prateritum: ['hieß'],
		partizip2: 'geheißen',
	},
	{
		id: 'helfen',
		infinitiv: 'helfen',
		translation: 'помогать',
		prateritum: ['half'],
		partizip2: 'geholfen',
	},
	{
		id: 'kennen',
		infinitiv: 'kennen',
		translation: 'знать (кого-то/что-то)',
		prateritum: ['kannte'],
		partizip2: 'gekannt',
	},
	{
		id: 'kommen',
		infinitiv: 'kommen',
		translation: 'приходить',
		prateritum: ['kam'],
		partizip2: 'gekommen',
	},
	{
		id: 'können',
		infinitiv: 'können',
		translation: 'мочь (быть способным)',
		prateritum: ['konnte'],
		partizip2: 'gekonnt',
	},
	{
		id: 'laden',
		infinitiv: 'laden',
		translation: 'грузить / заряжать',
		prateritum: ['lud'],
		partizip2: 'geladen',
	},
	{
		id: 'lassen',
		infinitiv: 'lassen',
		translation: 'позволять / оставлять',
		prateritum: ['ließ'],
		partizip2: 'gelassen',
	},
	{
		id: 'laufen',
		infinitiv: 'laufen',
		translation: 'бегать / ходить',
		prateritum: ['lief'],
		partizip2: 'gelaufen',
	},
	{
		id: 'leiden',
		infinitiv: 'leiden',
		translation: 'страдать',
		prateritum: ['litt'],
		partizip2: 'gelitten',
	},
	{
		id: 'leihen',
		infinitiv: 'leihen',
		translation: 'одалживать',
		prateritum: ['lieh'],
		partizip2: 'geliehen',
	},
	{
		id: 'lesen',
		infinitiv: 'lesen',
		translation: 'читать',
		prateritum: ['las'],
		partizip2: 'gelesen',
	},
	{
		id: 'liegen',
		infinitiv: 'liegen',
		translation: 'лежать',
		prateritum: ['lag'],
		partizip2: 'gelegen',
	},
	{
		id: 'lügen',
		infinitiv: 'lügen',
		translation: 'лгать',
		prateritum: ['log'],
		partizip2: 'gelogen',
	},
	{
		id: 'messen',
		infinitiv: 'messen',
		translation: 'измерять',
		prateritum: ['maß'],
		partizip2: 'gemessen',
	},
	{
		id: 'mögen',
		infinitiv: 'mögen',
		translation: 'любить / нравиться',
		prateritum: ['mochte'],
		partizip2: 'gemocht',
	},
	{
		id: 'müssen',
		infinitiv: 'müssen',
		translation: 'долженствовать / быть обязанным',
		prateritum: ['musste'],
		partizip2: 'gemusst',
	},
	{
		id: 'nehmen',
		infinitiv: 'nehmen',
		translation: 'брать',
		prateritum: ['nahm'],
		partizip2: 'genommen',
	},
	{
		id: 'nennen',
		infinitiv: 'nennen',
		translation: 'называть',
		prateritum: ['nannte'],
		partizip2: 'genannt',
	},
	{
		id: 'pfeifen',
		infinitiv: 'pfeifen',
		translation: 'свистеть',
		prateritum: ['pfiff'],
		partizip2: 'gepfiffen',
	},
	{
		id: 'raten',
		infinitiv: 'raten',
		translation: 'советовать / угадывать',
		prateritum: ['riet'],
		partizip2: 'geraten',
	},
	{
		id: 'reiten',
		infinitiv: 'reiten',
		translation: 'ехать верхом',
		prateritum: ['ritt'],
		partizip2: 'geritten',
	},
	{
		id: 'rennen',
		infinitiv: 'rennen',
		translation: 'бежать',
		prateritum: ['rannte'],
		partizip2: 'gerannt',
	},
	{
		id: 'riechen',
		infinitiv: 'riechen',
		translation: 'нюхать / пахнуть',
		prateritum: ['roch'],
		partizip2: 'gerochen',
	},
	{
		id: 'rufen',
		infinitiv: 'rufen',
		translation: 'звать / кричать',
		prateritum: ['rief'],
		partizip2: 'gerufen',
	},
	{
		id: 'schaffen',
		infinitiv: 'schaffen',
		translation: 'создавать / справляться',
		prateritum: ['schuf'],
		partizip2: 'geschaffen',
	},
	{
		id: 'scheinen',
		infinitiv: 'scheinen',
		translation: 'светить / казаться',
		prateritum: ['schien'],
		partizip2: 'geschienen',
	},
	{
		id: 'schieben',
		infinitiv: 'schieben',
		translation: 'толкать / двигать',
		prateritum: ['schob'],
		partizip2: 'geschoben',
	},
	{
		id: 'schlafen',
		infinitiv: 'schlafen',
		translation: 'спать',
		prateritum: ['schlief'],
		partizip2: 'geschlafen',
	},
	{
		id: 'schlagen',
		infinitiv: 'schlagen',
		translation: 'бить / ударять',
		prateritum: ['schlug'],
		partizip2: 'geschlagen',
	},
	{
		id: 'schleichen',
		infinitiv: 'schleichen',
		translation: 'красться',
		prateritum: ['schlich'],
		partizip2: 'geschlichen',
	},
	{
		id: 'schließen',
		infinitiv: 'schließen',
		translation: 'закрывать',
		prateritum: ['schloss'],
		partizip2: 'geschlossen',
	},
	{
		id: 'schlingen',
		infinitiv: 'schlingen',
		translation: 'обвивать',
		prateritum: ['schlang'],
		partizip2: 'geschlungen',
	},
	{
		id: 'schmeißen',
		infinitiv: 'schmeißen',
		translation: 'кидать / бросать',
		prateritum: ['schmiss'],
		partizip2: 'geschmissen',
	},
	{
		id: 'schmelzen',
		infinitiv: 'schmelzen',
		translation: 'таять / плавить',
		prateritum: ['schmolz'],
		partizip2: 'geschmolzen',
	},
	{
		id: 'schneiden',
		infinitiv: 'schneiden',
		translation: 'резать',
		prateritum: ['schnitt'],
		partizip2: 'geschnitten',
	},
	{
		id: 'schreiben',
		infinitiv: 'schreiben',
		translation: 'писать',
		prateritum: ['schrieb'],
		partizip2: 'geschrieben',
	},
	{
		id: 'schreien',
		infinitiv: 'schreien',
		translation: 'кричать',
		prateritum: ['schrie'],
		partizip2: 'geschrien',
	},
	{
		id: 'schreiten',
		infinitiv: 'schreiten',
		translation: 'шагать',
		prateritum: ['schritt'],
		partizip2: 'geschritten',
	},
	{
		id: 'schweigen',
		infinitiv: 'schweigen',
		translation: 'молчать',
		prateritum: ['schwieg'],
		partizip2: 'geschwiegen',
	},
	{
		id: 'schwellen',
		infinitiv: 'schwellen',
		translation: 'опухать',
		prateritum: ['schwoll'],
		partizip2: 'geschwollen',
	},
	{
		id: 'schwimmen',
		infinitiv: 'schwimmen',
		translation: 'плавать',
		prateritum: ['schwamm'],
		partizip2: 'geschwommen',
	},
	{
		id: 'schwinden',
		infinitiv: 'schwinden',
		translation: 'исчезать / убывать',
		prateritum: ['schwand'],
		partizip2: 'geschwunden',
	},
	{
		id: 'schwingen',
		infinitiv: 'schwingen',
		translation: 'качать',
		prateritum: ['schwang'],
		partizip2: 'geschwungen',
	},
	{
		id: 'schwören',
		infinitiv: 'schwören',
		translation: 'клясться',
		prateritum: ['schwor'],
		partizip2: 'geschworen',
	},
	{
		id: 'sehen',
		infinitiv: 'sehen',
		translation: 'видеть',
		prateritum: ['sah'],
		partizip2: 'gesehen',
	},
	{
		id: 'sein',
		infinitiv: 'sein',
		translation: 'быть',
		prateritum: ['war'],
		partizip2: 'gewesen',
	},
	{
		id: 'senden',
		infinitiv: 'senden',
		translation: 'отравлять / посылать',
		prateritum: ['sandte', 'sendete'],
		partizip2: ['gesendet'],
	},
	{
		id: 'singen',
		infinitiv: 'singen',
		translation: 'петь',
		prateritum: ['sang'],
		partizip2: 'gesungen',
	},
	{
		id: 'sinken',
		infinitiv: 'sinken',
		translation: 'опускаться / тонуть',
		prateritum: ['sank'],
		partizip2: 'gesunken',
	},
	{
		id: 'sinnen',
		infinitiv: 'sinnen',
		translation: 'размышлять',
		prateritum: ['sann'],
		partizip2: 'gesonnen',
	},
	{
		id: 'sitzen',
		infinitiv: 'sitzen',
		translation: 'сидеть',
		prateritum: ['saß'],
		partizip2: 'gesessen',
	},
	{
		id: 'sollen',
		infinitiv: 'sollen',
		translation: 'быть должным',
		prateritum: ['sollte'],
		partizip2: 'gesollt',
	},
	{
		id: 'speien',
		infinitiv: 'speien',
		translation: 'плевать / выплевывать',
		prateritum: ['spie'],
		partizip2: 'gespien',
	},
	{
		id: 'spinnen',
		infinitiv: 'spinnen',
		translation: 'прясть',
		prateritum: ['spann'],
		partizip2: 'gesponnen',
	},
	{
		id: 'sprechen',
		infinitiv: 'sprechen',
		translation: 'говорить',
		prateritum: ['sprach'],
		partizip2: 'gesprochen',
	},
	{
		id: 'sprießen',
		infinitiv: 'sprießen',
		translation: 'прорастать',
		prateritum: ['spross'],
		partizip2: 'gesprossen',
	},
	{
		id: 'springen',
		infinitiv: 'springen',
		translation: 'прыгать',
		prateritum: ['sprang'],
		partizip2: 'gesprungen',
	},
	{
		id: 'stechen',
		infinitiv: 'stechen',
		translation: 'колоть / жалить',
		prateritum: ['stach'],
		partizip2: 'gestochen',
	},
	{
		id: 'stehen',
		infinitiv: 'stehen',
		translation: 'стоять',
		prateritum: ['stand'],
		partizip2: 'gestanden',
	},
	{
		id: 'stehlen',
		infinitiv: 'stehlen',
		translation: 'воровать',
		prateritum: ['stahl'],
		partizip2: 'gestohlen',
	},
	{
		id: 'steigen',
		infinitiv: 'steigen',
		translation: 'подниматься',
		prateritum: ['stieg'],
		partizip2: 'gestiegen',
	},
	{
		id: 'sterben',
		infinitiv: 'sterben',
		translation: 'умирать',
		prateritum: ['starb'],
		partizip2: 'gestorben',
	},
	{
		id: 'stinken',
		infinitiv: 'stinken',
		translation: 'вонять',
		prateritum: ['stank'],
		partizip2: 'gestunken',
	},
	{
		id: 'stoßen',
		infinitiv: 'stoßen',
		translation: 'толкать',
		prateritum: ['stieß'],
		partizip2: 'gestoßen',
	},
	{
		id: 'streichen',
		infinitiv: 'streichen',
		translation: 'гладить / красить (противоположно колоть)',
		prateritum: ['strich'],
		partizip2: 'gestrichen',
	},
	{
		id: 'streiten',
		infinitiv: 'streiten',
		translation: 'спорить / ссориться',
		prateritum: ['stritt'],
		partizip2: 'gestritten',
	},
	{
		id: 'tragen',
		infinitiv: 'tragen',
		translation: 'носить',
		prateritum: ['trug'],
		partizip2: 'getragen',
	},
	{
		id: 'treffen',
		infinitiv: 'treffen',
		translation: 'встречать / попадать',
		prateritum: ['traf'],
		partizip2: 'getroffen',
	},
	{
		id: 'treiben',
		infinitiv: 'treiben',
		translation: 'гнать / заниматься (чем-либо)',
		prateritum: ['trieb'],
		partizip2: 'getrieben',
	},
	{
		id: 'treten',
		infinitiv: 'treten',
		translation: 'ступать',
		prateritum: ['trat'],
		partizip2: 'getreten',
	},
	{
		id: 'trinken',
		infinitiv: 'trinken',
		translation: 'пить',
		prateritum: ['trank'],
		partizip2: 'getrunken',
	},
	{
		id: 'trügen',
		infinitiv: 'trügen',
		translation: 'обманывать / вводить в заблуждение',
		prateritum: ['trog'],
		partizip2: 'getrogen',
	},
	{
		id: 'tun',
		infinitiv: 'tun',
		translation: 'делать',
		prateritum: ['tat'],
		partizip2: 'getan',
	},
	{
		id: 'verderben',
		infinitiv: 'verderben',
		translation: 'портить',
		prateritum: ['verdarb'],
		partizip2: 'verdorben',
	},
	{
		id: 'vergessen',
		infinitiv: 'vergessen',
		translation: 'забывать',
		prateritum: ['vergaß'],
		partizip2: 'vergessen',
	},
	{
		id: 'verlieren',
		infinitiv: 'verlieren',
		translation: 'терять / проигрывать',
		prateritum: ['verlor'],
		partizip2: 'verloren',
	},
	{
		id: 'verzeihen',
		infinitiv: 'verzeihen',
		translation: 'прощать',
		prateritum: ['verzieh'],
		partizip2: 'verziehen',
	},
	{
		id: 'wachsen',
		infinitiv: 'wachsen',
		translation: 'расти',
		prateritum: ['wuchs'],
		partizip2: 'gewachsen',
	},
	{
		id: 'waschen',
		infinitiv: 'waschen',
		translation: 'мыть / стирать',
		prateritum: ['wusch'],
		partizip2: 'gewaschen',
	},
	{
		id: 'weichen',
		infinitiv: 'weichen',
		translation: 'смягчать / уступать',
		prateritum: ['wich'],
		partizip2: 'gewichen',
	},
	{
		id: 'weisen',
		infinitiv: 'weisen',
		translation: 'указывать',
		prateritum: ['wies'],
		partizip2: 'gewiesen',
	},
	{
		id: 'wenden',
		infinitiv: 'wenden',
		translation: 'поворачивать',
		prateritum: ['wandte', 'wendete'],
		partizip2: ['gewendet'],
	},
	{
		id: 'werben',
		infinitiv: 'werben',
		translation: 'рекламировать / вербовать',
		prateritum: ['warb'],
		partizip2: 'geworben',
	},
	{
		id: 'werden',
		infinitiv: 'werden',
		translation: 'становиться',
		prateritum: ['wurde'],
		partizip2: 'geworden',
	},
	{
		id: 'werfen',
		infinitiv: 'werfen',
		translation: 'бросать',
		prateritum: ['warf'],
		partizip2: 'geworfen',
	},
	{
		id: 'wiegen',
		infinitiv: 'wiegen',
		translation: 'весить / взвешивать',
		prateritum: ['wog'],
		partizip2: 'gewogen',
	},
	{
		id: 'winden',
		infinitiv: 'winden',
		translation: 'скручивать / мотать',
		prateritum: ['wand'],
		partizip2: 'gewunden',
	},
	{
		id: 'wissen',
		infinitiv: 'wissen',
		translation: 'знать (факт)',
		prateritum: ['wusste'],
		partizip2: 'gewusst',
	},
	{
		id: 'wollen',
		infinitiv: 'wollen',
		translation: 'хотеть',
		prateritum: ['wollte'],
		partizip2: 'gewollt',
	},
	{
		id: 'wringen',
		infinitiv: 'wringen',
		translation: 'отжимать',
		prateritum: ['wrang'],
		partizip2: 'gewrungen',
	},
	{
		id: 'ziehen',
		infinitiv: 'ziehen',
		translation: 'тянуть',
		prateritum: ['zog'],
		partizip2: 'gezogen',
	},
	{
		id: 'zwingen',
		infinitiv: 'zwingen',
		translation: 'вынуждать',
		prateritum: ['zwang'],
		partizip2: 'gezwungen',
	},
];
