export const VERB_GR1 = [
	{
		id: 'gleichen',
		infinitiv: 'gleichen',
		translation: 'походить / быть похожим',
		prateritum: ['glich'],
		partizip2: 'geglichen',
	},
	{
		id: 'angreifen',
		infinitiv: 'angreifen',
		translation: 'атаковать / нападать',
		prateritum: ['griff an'],
		partizip2: 'angegriffen',
	},
	{
		id: 'leiden',
		infinitiv: 'leiden',
		translation: 'страдать',
		prateritum: ['litt'],
		partizip2: 'gelitten',
	},
	{
		id: 'schneiden',
		infinitiv: 'schneiden',
		translation: 'резать',
		prateritum: ['schnitt'],
		partizip2: 'geschnitten',
	},
	{
		id: 'streiten',
		infinitiv: 'streiten',
		translation: 'спорить / ссориться',
		prateritum: ['stritt'],
		partizip2: 'gestritten',
	},
];

export const VERB_GR2 = [
	{
		id: 'beweisen',
		infinitiv: 'beweisen',
		translation: 'доказывать',
		prateritum: ['bewies'],
		partizip2: 'bewiesen',
	},
	{
		id: 'bleiben',
		infinitiv: 'bleiben',
		translation: 'оставаться',
		prateritum: ['blieb'],
		partizip2: 'geblieben',
	},
	{
		id: 'entscheiden',
		infinitiv: 'entscheiden',
		translation: 'решать / принимать решение',
		prateritum: ['entschied'],
		partizip2: 'entschieden',
	},
	{
		id: 'heißen',
		infinitiv: 'heißen',
		translation: 'называться / означать',
		prateritum: ['hieß'],
		partizip2: 'geheißen',
	},
	{
		id: 'leihen',
		infinitiv: 'leihen',
		translation: 'одалживать / брать взаймы',
		prateritum: ['lieh'],
		partizip2: 'geliehen',
	},
	{
		id: 'scheinen',
		infinitiv: 'scheinen',
		translation: 'светить / казаться',
		prateritum: ['schien'],
		partizip2: 'geschienen',
	},
	{
		id: 'schreiben',
		infinitiv: 'schreiben',
		translation: 'писать',
		prateritum: ['schrieb'],
		partizip2: 'geschrieben',
	},
	{
		id: 'schreien',
		infinitiv: 'schreien',
		translation: 'кричать',
		prateritum: ['schrie'],
		partizip2: 'geschrien',
	},
	{
		id: 'schweigen',
		infinitiv: 'schweigen',
		translation: 'молчать',
		prateritum: ['schwieg'],
		partizip2: 'geschwiegen',
	},
	{
		id: 'steigen',
		infinitiv: 'steigen',
		translation: 'подниматься / взбираться',
		prateritum: ['stieg'],
		partizip2: 'gestiegen',
	},
	{
		id: 'treiben',
		infinitiv: 'treiben',
		translation: 'гнать / заниматься чем-либо',
		prateritum: ['trieb'],
		partizip2: 'getrieben',
	},
	{
		id: 'verzeihen',
		infinitiv: 'verzeihen',
		translation: 'прощать',
		prateritum: ['verzieh'],
		partizip2: 'verziehen',
	},
];

export const VERB_GR3 = [
	{
		id: 'verbinden',
		infinitiv: 'verbinden',
		translation: 'соединять / связывать',
		prateritum: ['verband'],
		partizip2: 'verbunden',
	},
	{
		id: 'finden',
		infinitiv: 'finden',
		translation: 'находить',
		prateritum: ['fand'],
		partizip2: 'gefunden',
	},
	{
		id: 'gelingen',
		infinitiv: 'gelingen',
		translation: 'удаваться',
		prateritum: ['gelang'],
		partizip2: 'gelungen',
	},
	{
		id: 'singen',
		infinitiv: 'singen',
		translation: 'петь',
		prateritum: ['sang'],
		partizip2: 'gesungen',
	},
	{
		id: 'sinken',
		infinitiv: 'sinken',
		translation: 'тонуть / снижаться',
		prateritum: ['sank'],
		partizip2: 'gesunken',
	},
	{
		id: 'springen',
		infinitiv: 'springen',
		translation: 'прыгать',
		prateritum: ['sprang'],
		partizip2: 'gesprungen',
	},
	{
		id: 'stinken',
		infinitiv: 'stinken',
		translation: 'вонять',
		prateritum: ['stank'],
		partizip2: 'gestunken',
	},
	{
		id: 'trinken',
		infinitiv: 'trinken',
		translation: 'пить',
		prateritum: ['trank'],
		partizip2: 'getrunken',
	},
	{
		id: 'zwingen',
		infinitiv: 'zwingen',
		translation: 'заставлять / принуждать',
		prateritum: ['zwang'],
		partizip2: 'gezwungen',
	},
];

export const VERB_GR4 = [
	{
		id: 'beginnen',
		infinitiv: 'beginnen',
		translation: 'начинать',
		prateritum: ['begann'],
		partizip2: 'begonnen',
	},
	{
		id: 'gewinnen',
		infinitiv: 'gewinnen',
		translation: 'выигрывать / побеждать',
		prateritum: ['gewann'],
		partizip2: 'gewonnen',
	},
	{
		id: 'schwimmen',
		infinitiv: 'schwimmen',
		translation: 'плавать',
		prateritum: ['schwamm'],
		partizip2: 'geschwommen',
	},
	{
		id: 'gebären',
		infinitiv: 'gebären',
		translation: 'рожать',
		prateritum: ['gebar'],
		partizip2: 'geboren',
	},
	{
		id: 'kommen',
		infinitiv: 'kommen',
		translation: 'приходить / приезжать',
		prateritum: ['kam'],
		partizip2: 'gekommen',
	},
];

export const VERB_GR5 = [
	{
		id: 'backen',
		infinitiv: 'backen',
		translation: 'печь',
		prateritum: ['buk', 'backte'],
		partizip2: 'gebacken',
	},
	{
		id: 'fahren',
		infinitiv: 'fahren',
		translation: 'ехать / водить',
		prateritum: ['fuhr'],
		partizip2: 'gefahren',
	},
	{
		id: 'einladen',
		infinitiv: 'einladen',
		translation: 'приглашать',
		prateritum: ['lud ein'],
		partizip2: 'eingeladen',
	},
	{
		id: 'schlagen',
		infinitiv: 'schlagen',
		translation: 'бить / ударять',
		prateritum: ['schlug'],
		partizip2: 'geschlagen',
	},
	{
		id: 'tragen',
		infinitiv: 'tragen',
		translation: 'носить',
		prateritum: ['trug'],
		partizip2: 'getragen',
	},
	{
		id: 'wachsen',
		infinitiv: 'wachsen',
		translation: 'расти',
		prateritum: ['wuchs'],
		partizip2: 'gewachsen',
	},
	{
		id: 'wachsen2',
		infinitiv: 'wachsen',
		translation: 'воcком покрывать / натирать',
		prateritum: ['wachste'],
		partizip2: 'gewachst',
	},
	{
		id: 'waschen',
		infinitiv: 'waschen',
		translation: 'мыть / стирать',
		prateritum: ['wusch'],
		partizip2: 'gewaschen',
	},
];

export const VERB_GR6 = [
	{
		id: 'biegen',
		infinitiv: 'biegen',
		translation: 'гнуть / поворачивать',
		prateritum: ['bog'],
		partizip2: 'gebogen',
	},
	{
		id: 'bieten',
		infinitiv: 'bieten',
		translation: 'предлагать',
		prateritum: ['bot'],
		partizip2: 'geboten',
	},
	{
		id: 'fliegen',
		infinitiv: 'fliegen',
		translation: 'летать',
		prateritum: ['flog'],
		partizip2: 'geflogen',
	},
	{
		id: 'fließen',
		infinitiv: 'fließen',
		translation: 'течь',
		prateritum: ['floss'],
		partizip2: 'geflossen',
	},
	{
		id: 'frieren',
		infinitiv: 'frieren',
		translation: 'замерзать / мёрзнуть',
		prateritum: ['fror'],
		partizip2: 'gefroren',
	},
	{
		id: 'riechen',
		infinitiv: 'riechen',
		translation: 'нюхать / пахнуть',
		prateritum: ['roch'],
		partizip2: 'gerochen',
	},
	{
		id: 'schieben',
		infinitiv: 'schieben',
		translation: 'толкать / двигать',
		prateritum: ['schob'],
		partizip2: 'geschoben',
	},
	{
		id: 'schließen',
		infinitiv: 'schließen',
		translation: 'закрывать',
		prateritum: ['schloss'],
		partizip2: 'geschlossen',
	},
	{
		id: 'verlieren',
		infinitiv: 'verlieren',
		translation: 'терять',
		prateritum: ['verlor'],
		partizip2: 'verloren',
	},
	{
		id: 'wiegen',
		infinitiv: 'wiegen',
		translation: 'весить / взвешивать',
		prateritum: ['wog'],
		partizip2: 'gewogen',
	},
	{
		id: 'ziehen',
		infinitiv: 'ziehen',
		translation: 'тянуть / переезжать',
		prateritum: ['zog'],
		partizip2: 'gezogen',
	},
	{
		id: 'heben',
		infinitiv: 'heben',
		translation: 'поднимать',
		prateritum: ['hob'],
		partizip2: 'gehoben',
	},
	{
		id: 'betrügen',
		infinitiv: 'betrügen',
		translation: 'обманывать',
		prateritum: ['betrog'],
		partizip2: 'betrogen',
	},
	{
		id: 'lügen',
		infinitiv: 'lügen',
		translation: 'лгать',
		prateritum: ['log'],
		partizip2: 'gelogen',
	},
];

export const VERB_GR7 = [
	{
		id: 'essen',
		infinitiv: 'essen',
		translation: 'есть (кушать)',
		prateritum: ['aß'],
		partizip2: 'gegessen',
	},
	{
		id: 'fressen',
		infinitiv: 'fressen',
		translation: 'жрать (о животных)',
		prateritum: ['fraß'],
		partizip2: 'gefressen',
	},
	{
		id: 'geben',
		infinitiv: 'geben',
		translation: 'давать',
		prateritum: ['gab'],
		partizip2: 'gegeben',
	},
	{
		id: 'geschehen',
		infinitiv: 'geschehen',
		translation: 'случаться / происходить',
		prateritum: ['geschah'],
		partizip2: 'geschehen',
	},
	{
		id: 'lesen',
		infinitiv: 'lesen',
		translation: 'читать',
		prateritum: ['las'],
		partizip2: 'gelesen',
	},
	{
		id: 'messen',
		infinitiv: 'messen',
		translation: 'измерять',
		prateritum: ['maß'],
		partizip2: 'gemessen',
	},
	{
		id: 'sehen',
		infinitiv: 'sehen',
		translation: 'видеть',
		prateritum: ['sah'],
		partizip2: 'gesehen',
	},
	{
		id: 'treten',
		infinitiv: 'treten',
		translation: 'ступать / наступать',
		prateritum: ['trat'],
		partizip2: 'getreten',
	},
	{
		id: 'vergessen',
		infinitiv: 'vergessen',
		translation: 'забывать',
		prateritum: ['vergaß'],
		partizip2: 'vergessen',
	},
];

export const VERB_GR8 = [
	{
		id: 'bewerben',
		infinitiv: 'sich bewerben',
		translation: 'подавать заявление / устраиваться',
		prateritum: ['bewarb sich'],
		partizip2: 'beworben',
	},
	{
		id: 'brechen',
		infinitiv: 'brechen',
		translation: 'ломать / разбивать',
		prateritum: ['brach'],
		partizip2: 'gebrochen',
	},
	{
		id: 'empfehlen',
		infinitiv: 'empfehlen',
		translation: 'рекомендовать',
		prateritum: ['empfahl'],
		partizip2: 'empfohlen',
	},
	{
		id: 'erschrecken1',
		infinitiv: 'erschrecken',
		translation: 'испугаться',
		prateritum: ['erschrak'],
		partizip2: 'erschrocken',
	},
	{
		id: 'erschrecken2',
		infinitiv: 'erschrecken',
		translation: 'пугать кого-то',
		prateritum: ['erschreckte'],
		partizip2: 'erschreckt',
	},
	{
		id: 'gelten',
		infinitiv: 'gelten',
		translation: 'считаться / иметь силу',
		prateritum: ['galt'],
		partizip2: 'gegolten',
	},
	{
		id: 'helfen',
		infinitiv: 'helfen',
		translation: 'помогать',
		prateritum: ['half'],
		partizip2: 'geholfen',
	},
	{
		id: 'nehmen',
		infinitiv: 'nehmen',
		translation: 'брать',
		prateritum: ['nahm'],
		partizip2: 'genommen',
	},
	{
		id: 'sprechen',
		infinitiv: 'sprechen',
		translation: 'говорить',
		prateritum: ['sprach'],
		partizip2: 'gesprochen',
	},
	{
		id: 'stehlen',
		infinitiv: 'stehlen',
		translation: 'красть',
		prateritum: ['stahl'],
		partizip2: 'gestohlen',
	},
	{
		id: 'sterben',
		infinitiv: 'sterben',
		translation: 'умирать',
		prateritum: ['starb'],
		partizip2: 'gestorben',
	},
	{
		id: 'treffen',
		infinitiv: 'treffen',
		translation: 'встречать',
		prateritum: ['traf'],
		partizip2: 'getroffen',
	},
	{
		id: 'werfen',
		infinitiv: 'werfen',
		translation: 'бросать',
		prateritum: ['warf'],
		partizip2: 'geworfen',
	},
];

export const VERB_GR9 = [
	{
		id: 'anfangen',
		infinitiv: '(an)fangen',
		translation: 'начинать',
		prateritum: ['fing (... an)'],
		partizip2: '(an)gefangen',
	},
	{
		id: 'hängen1',
		infinitiv: 'hängen',
		translation: 'висеть',
		prateritum: ['hing'],
		partizip2: 'gehangen',
	},
	{
		id: 'hängen2',
		infinitiv: 'hängen',
		translation: 'вешать',
		prateritum: ['hängte'],
		partizip2: 'gehängt',
	},
	{
		id: 'braten',
		infinitiv: 'braten',
		translation: 'жарить',
		prateritum: ['briet'],
		partizip2: 'gebraten',
	},
	{
		id: 'fallen',
		infinitiv: 'fallen',
		translation: 'падать',
		prateritum: ['fiel'],
		partizip2: 'gefallen',
	},
	{
		id: 'halten',
		infinitiv: 'halten',
		translation: 'держать / останавливаться',
		prateritum: ['hielt'],
		partizip2: 'gehalten',
	},
	{
		id: 'lassen',
		infinitiv: 'lassen',
		translation: 'позволять / оставлять',
		prateritum: ['ließ'],
		partizip2: 'gelassen',
	},
	{
		id: 'raten',
		infinitiv: 'raten',
		translation: 'советовать / угадывать',
		prateritum: ['riet'],
		partizip2: 'geraten',
	},
	{
		id: 'schlafen',
		infinitiv: 'schlafen',
		translation: 'спать',
		prateritum: ['schlief'],
		partizip2: 'geschlafen',
	},
	{
		id: 'gehen',
		infinitiv: 'gehen',
		translation: 'идти / ходить',
		prateritum: ['ging'],
		partizip2: 'gegangen',
	},
];

export const VERB_GR10 = [
	{
		id: 'rufen',
		infinitiv: 'rufen',
		translation: 'звать / кричать',
		prateritum: ['rief'],
		partizip2: 'gerufen',
	},
	{
		id: 'tun',
		infinitiv: 'tun',
		translation: 'делать',
		prateritum: ['tat'],
		partizip2: 'getan',
	},
	{
		id: 'laufen',
		infinitiv: 'laufen',
		translation: 'бегать / ходить',
		prateritum: ['lief'],
		partizip2: 'gelaufen',
	},
];

export const VERB_GR11 = [
	{
		id: 'bitten',
		infinitiv: 'bitten',
		translation: 'просить',
		prateritum: ['bat'],
		partizip2: 'gebeten',
	},
	{
		id: 'sitzen',
		infinitiv: 'sitzen',
		translation: 'сидеть',
		prateritum: ['saß'],
		partizip2: 'gesessen',
	},
	{
		id: 'liegen',
		infinitiv: 'liegen',
		translation: 'лежать',
		prateritum: ['lag'],
		partizip2: 'gelegen',
	},
];

export const VERB_GR12 = [
	{
		id: 'brennen',
		infinitiv: 'brennen',
		translation: 'гореть',
		prateritum: ['brannte'],
		partizip2: 'gebrannt',
	},
	{
		id: 'denken',
		infinitiv: 'denken',
		translation: 'думать',
		prateritum: ['dachte'],
		partizip2: 'gedacht',
	},
	{
		id: 'kennen',
		infinitiv: 'kennen',
		translation: 'знать (кого-то, что-то)',
		prateritum: ['kannte'],
		partizip2: 'gekannt',
	},
	{
		id: 'nennen',
		infinitiv: 'nennen',
		translation: 'называть',
		prateritum: ['nannte'],
		partizip2: 'genannt',
	},
	{
		id: 'rennen',
		infinitiv: 'rennen',
		translation: 'бежать',
		prateritum: ['rannte'],
		partizip2: 'gerannt',
	},
	{
		id: 'senden1',
		infinitiv: 'senden',
		translation: 'посылать (устар./лит.)',
		prateritum: ['sandte'],
		partizip2: 'gesandt',
	},
	{
		id: 'senden2',
		infinitiv: 'senden',
		translation: 'отправлять (техн./совр.)',
		prateritum: ['sendete'],
		partizip2: 'gesendet',
	},
	{
		id: 'stehen',
		infinitiv: 'stehen',
		translation: 'стоять',
		prateritum: ['stand'],
		partizip2: 'gestanden',
	},
	{
		id: 'bringen',
		infinitiv: 'bringen',
		translation: 'приносить',
		prateritum: ['brachte'],
		partizip2: 'gebracht',
	},
];

export const VERB_GR13 = [
	{
		id: 'haben',
		infinitiv: 'haben',
		translation: 'иметь',
		prateritum: ['hatte'],
		partizip2: 'gehabt',
	},
	{
		id: 'sein',
		infinitiv: 'sein',
		translation: 'быть',
		prateritum: ['war'],
		partizip2: 'gewesen',
	},
	{
		id: 'werden',
		infinitiv: 'werden',
		translation: 'становиться',
		prateritum: ['wurde'],
		partizip2: 'geworden',
	},
	{
		id: 'sollen',
		infinitiv: 'sollen',
		translation: 'долженствовать',
		prateritum: ['sollte'],
		partizip2: 'gesollt',
	},
	{
		id: 'wollen',
		infinitiv: 'wollen',
		translation: 'хотеть',
		prateritum: ['wollte'],
		partizip2: 'gewollt',
	},
	{
		id: 'können',
		infinitiv: 'können',
		translation: 'мочь / уметь',
		prateritum: ['konnte'],
		partizip2: 'gekonnt',
	},
	{
		id: 'dürfen',
		infinitiv: 'dürfen',
		translation: 'мочь (разрешено)',
		prateritum: ['durfte'],
		partizip2: 'gedurft',
	},
	{
		id: 'müssen',
		infinitiv: 'müssen',
		translation: 'долженствовать (необходимо)',
		prateritum: ['musste'],
		partizip2: 'gemusst',
	},
	{
		id: 'mögen',
		infinitiv: 'mögen',
		translation: 'любить / нравиться',
		prateritum: ['mochte'],
		partizip2: 'gemocht',
	},
	{
		id: 'wissen',
		infinitiv: 'wissen',
		translation: 'знать (факты)',
		prateritum: ['wusste'],
		partizip2: 'gewusst',
	},
];
